import { Router } from 'express';
import user from './user';
import oauth from './oauth';
import wallet from './wallet';
import bankAccount from './bank_account';
import withdrawal from './withdrawal';
import transaction from './transaction';
import lottery from './lottery';
import text from './text';
import borletteTicket from './borlette_ticket';
import megamillionTicket from './megamillion_ticket';
import rouletteTicket from './roulette_ticket';
import roulette from './roulette';
import domino from './domino';
import notification from './notification';
import plan from './plan';
import loyalty from './loyalty';
import payoutConfig from './payout_config';
import message from './message';
import adminUserManagement from './admin/user-management';
import adminStateManagement from './admin/state-management';
import adminTierManagement from './admin/tier-management';
import adminBorletteManagement from './admin/borlette-management';
import adminMegamillionManagement from './admin/megamillion-management';
import adminRouletteManagement from './admin/roulette-management';
import adminDominoManagement from './admin/domino-management';
import adminGlobalChatManagement from './admin/global-chat-management';
import adminMessageManagement from './admin/message-management';
import globalChat from './global_chat';
import invite from './invite';

const router = new Router();

router.use('/user', user);
router.use('/oauth', oauth);
router.use('/lottery', lottery);
router.use('/ticket/borlette', borletteTicket);
router.use('/ticket/megamillion', megamillionTicket);
router.use('/wallet', wallet);
router.use('/roulette', roulette);
router.use('/transaction', transaction);
router.use('/notification', notification);
router.use('/bank-accounts', bankAccount);
router.use('/roulette-ticket', rouletteTicket);
router.use('/withdrawals', withdrawal);
router.use('/domino', domino);
router.use('/text', text);
router.use('/loyalty', loyalty);
router.use('/plan', plan);
router.use('/payout-config', payoutConfig);
router.use('/messages', message);
router.use('/invite', invite);
router.use('/admin/users', adminUserManagement);
router.use('/admin/tiers', adminTierManagement);
router.use('/admin/states', adminStateManagement);
router.use('/admin/borlette-management', adminBorletteManagement);
router.use('/admin/megamillion-management', adminMegamillionManagement);
router.use('/admin/roulette-management', adminRouletteManagement);
router.use('/admin/domino-management', adminDominoManagement);
router.use('/admin/global-chat-management', adminGlobalChatManagement);
router.use('/admin/message-management', adminMessageManagement);
router.use('/global-chat', globalChat);

export default router;
